### PR TITLE
Added compatibility with FreeRTOS base Pebble Time uses

### PR DESCRIPTION
**Pull request by Avamander**
From https://www.gnu.org/licenses/license-list.en.html: 

> Please note that GPLv3 is not compatible with GPLv2 by itself. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well. When this is the case, you can use the code under GPLv3 to make the desired combination. To learn more about compatibility between GNU licenses, please see our FAQ.

https://github.com/ginge/FreeRTOS-Pebble

### CODE REVIEW

**Comment by Avamander** [comment]
My bad, didn't see the clause in the files that allowed this. Though the circle.c, circle.h, rect.c, rect.h, path.h and path.c files lack the clause thus don't allow using it alongside GPLv3 code.

**Comment by jneubrand** [comment]
I'll add them.

**Comment by jneubrand** [comment]
closed via e40f0b4

**Comment by Avamander** [comment]
Path.c and path.h still lack the clause, also, the license file should be named "LICENSE" to make Github recognize it (shows the license in the header then).

**Comment by jneubrand** [comment]
fixed all of those :)

**Pull request closed without merging**
